import React from 'react';
import ReactMarkdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import rehypeRaw from 'rehype-raw';
import remarkGfm from 'remark-gfm';
import { PreviewProps } from '../types';

const Preview: React.FC<PreviewProps> = ({ markdown, theme }) => {
  return (
    <div className="w-full h-full bg-white overflow-y-auto">
        {/* 
            This ID is crucial for the export function. 
            The styles are applied via the `components` prop of ReactMarkdown 
            to ensure they are inline on the DOM elements.
        */}
      <div 
        id="wechat-preview-content" 
        className="px-4 py-6 min-h-full"
        style={{ backgroundColor: '#fff' }}
      >
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          rehypePlugins={[rehypeHighlight, rehypeRaw]}
          components={{
            h1: ({node, ...props}) => <h1 style={theme.h1} {...props} />,
            h2: ({node, children, ...props}) => (
              <h2 style={theme.h2} {...props}>
                {theme.h2Prefix && <span style={{ marginRight: '6px' }}>{theme.h2Prefix}</span>}
                {children}
              </h2>
            ),
            h3: ({node, ...props}) => <h3 style={theme.h3} {...props} />,
            p: ({node, ...props}) => <p style={theme.p} {...props} />,
            blockquote: ({node, ...props}) => <blockquote style={theme.blockquote} {...props} />,
            ul: ({node, ...props}) => <ul style={{ paddingLeft: '20px', margin: '10px 0' }} {...props} />,
            ol: ({node, ...props}) => <ol style={{ paddingLeft: '20px', margin: '10px 0' }} {...props} />,
            li: ({node, ...props}) => <li style={theme.li} {...props} />,
            img: ({node, ...props}) => <img style={theme.img} {...props} alt="wx-img" />,
            code: ({ className, children, ...props }: any) => {
              const match = /language-(\w+)/.exec(className || '')
              const isInline = !match && !String(children).includes('\n');
              if (isInline) {
                  return <code style={theme.codeInline} {...props}>{children}</code>
              }
              return (
                <code className={className} style={{fontFamily: 'Menlo, Monaco, monospace', fontSize: '13px'}} {...props}>
                  {children}
                </code>
              )
            },
            pre: ({node, ...props}) => <pre style={theme.pre} {...props} />,
            a: ({node, ...props}) => <a style={theme.link} {...props} />,
            table: ({node, ...props}) => <table style={theme.table} {...props} />,
            th: ({node, ...props}) => <th style={theme.th} {...props} />,
            td: ({node, ...props}) => <td style={theme.td} {...props} />,
            tr: ({node, ...props}) => <tr style={{ borderBottom: '1px solid #eee' }} {...props} />,
            tbody: ({node, ...props}) => <tbody style={{ border: 'none' }} {...props} />,
            thead: ({node, ...props}) => <thead style={{ border: 'none' }} {...props} />,
          }}
        >
          {markdown}
        </ReactMarkdown>
        
        {/* Signature / Footer spacer */}
        <div style={{ marginTop: '40px', textAlign: 'center', color: '#ccc', fontSize: '12px' }}>
          Generated by WeChat MD Editor
        </div>
      </div>
    </div>
  );
};

export default Preview;